const defaultSchemeDefinitions = [
  {
    name: "Subsidy Support",
    description: "Support for verified low-income applicants.",
    eligibilityHint: "Eligible when verified annual income is Rs. 2,50,000 or below.",
    requiredDocuments: ["aadhaar", "pan", "income_certificate"],
    ruleType: "income",
    incomeThreshold: 250000,
    inclusive: true,
    approvalReason: "Verified income is within Rs. 2,50,000. The citizen is eligible for the subsidy scheme.",
    rejectionReason: "Income exceeds the Rs. 2,50,000 subsidy limit.",
    active: true,
  },
  {
    name: "Education Loan",
    description: "Education-loan support for applicants below the configured income threshold.",
    eligibilityHint: "Eligible when verified annual income is below Rs. 5,00,000.",
    requiredDocuments: ["aadhaar", "pan", "income_certificate"],
    ruleType: "income",
    incomeThreshold: 500000,
    inclusive: false,
    approvalReason:
      "Verified income is below Rs. 5,00,000. Eligible to apply for an education loan up to Rs. 6,00,000.",
    rejectionReason: "Verified income is not below Rs. 5,00,000, so the education loan benefit is not available.",
    active: true,
  },
  {
    name: "Housing Assistance",
    description: "Housing support for verified applicants with moderate income.",
    eligibilityHint: "Eligible when verified annual income is Rs. 3,00,000 or below.",
    requiredDocuments: ["aadhaar", "pan", "income_certificate"],
    ruleType: "income",
    incomeThreshold: 300000,
    inclusive: true,
    approvalReason: "Verified income is within Rs. 3,00,000. Eligible for housing assistance.",
    rejectionReason: "Income exceeds the Rs. 3,00,000 limit for housing assistance.",
    active: true,
  },
  {
    name: "Farmer Support",
    description: "Income-based support for eligible rural and agricultural households.",
    eligibilityHint: "Eligible when verified annual income is Rs. 3,50,000 or below.",
    requiredDocuments: ["aadhaar", "pan", "income_certificate"],
    ruleType: "income",
    incomeThreshold: 350000,
    inclusive: true,
    approvalReason: "Verified income is within Rs. 3,50,000. Eligible for farmer support benefits.",
    rejectionReason: "Income exceeds the Rs. 3,50,000 limit for farmer support.",
    active: true,
  },
  {
    name: "Health Care Aid",
    description: "Financial support for verified families seeking medical assistance.",
    eligibilityHint: "Eligible when verified annual income is Rs. 4,00,000 or below.",
    requiredDocuments: ["aadhaar", "pan", "income_certificate"],
    ruleType: "income",
    incomeThreshold: 400000,
    inclusive: true,
    approvalReason: "Verified income is within Rs. 4,00,000. Eligible for health care aid.",
    rejectionReason: "Income exceeds the Rs. 4,00,000 limit for health care aid.",
    active: true,
  },
  {
    name: "Senior Pension",
    description: "Pension support for senior applicants using Aadhaar and birth-certificate age verification.",
    eligibilityHint: "Eligible when verified age is 60 years or above.",
    requiredDocuments: ["aadhaar", "birth_certificate"],
    ruleType: "age",
    minimumAge: 60,
    inclusive: true,
    approvalReason: "Date of birth confirms the citizen is 60 or older and eligible for senior pension.",
    rejectionReason: "Citizen is below the senior pension age requirement of 60 years.",
    active: true,
  },
];

module.exports = {
  defaultSchemeDefinitions,
};
